### ISSUE TITLE
Saving Task List (Sprint 11/22/21)

### ISSUE THREAD

**Issue by braydenflaig** [COSC481W-2021Fall/capstone-thriving-5#48]
As a user, I would like to keep my list data even after signing out. 

Acceptance Criteria:
1. Saves task list data to phone database
2. Retrieves same task data upon login

Task List:
- [x] Store task list data to the phone database (Brayden)
- [x] Get task data upon login for the user (Chris)
- [x] Try to store in the backend if time allows (Chris and Brayden)
